project: "DBC-ICLR"
program: dbc/main.py
method: grid
name: "HalfCheetah-v3_dp"

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "dp"
  alg:
    value: "dp"
  traj-load-path:
    value: "/home/mhhsu/dbc-private/expert_datasets/halfcheetah_5trajs_processed.pt"
  env-name:
    value: "HalfCheetah-v3"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 10000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-eval:
    value: 10
  num-render:
    value: 0
  vid-fps:
    value: 100
  lr:
    value: 0.0001
  log-interval:
    value: 500
  save-interval:
    value: 100000
  eval-interval:
    value: 4000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  hidden-dim:
    value: 1200
  depth:
    value: 4
