project: 'diffusion'
program: dbc/main.py
method: grid
name: Push-bc-1.5-noDacay

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "bc"
  alg:
    value: "bc"
  traj-load-path:
    value: "./expert_datasets/push_10000_clip.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 2
  vid-fps:
    value: 100
  lr:
    value: 0.00001
  linear-lr-decay:
    value: False
  log-interval:
    value: 2000
  save-interval:
    value: 100000
  eval-interval:
    value: 4000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  hidden-dim:
    value: 1024
  depth:
    value: 1
  max-grad-norm:
    value: -1
  noise-ratio: 
    value: 1.5
  goal-noise-ratio:
    value: 1.5
