project: 'diffusion'
program: dbc/main.py
method: grid
name: Push-diP-1.50

parameters:
  seed:
    # values: [1, 2, 3]
    value: 1
  prefix:
    value: "dp"
  alg:
    value: "dp"
  use-proper-time-limits:
    value: True
  traj-load-path:
    value: "./expert_datasets/push_10000_clip.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 15000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  vid-fps:
    value: 30
  num-eval:
    value: 10
  lr:
    value: 0.00002
    # values: [0.0001, 0.00001,]
  log-interval:
    value: 3000
  save-interval:
    value: 500000
  eval-interval:
    value: 9000
  hidden-dim:
    value: 1200
  depth:
    value: 4
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  traj-batch-size:
    value: 128
  noise-ratio: 
    value: 1.50
  goal-noise-ratio:
    value: 1.50
