project: 'diffusion'
program: dbc/main.py
method: grid
name: Push-ibc-2.00

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "ibc"
  alg:
    value: "ibc"
  use-proper-time-limits:
    value: True
  traj-load-path:
    value: "./expert_datasets/push_10000_clip.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 15000
  cuda:
    value: True
  num-process:
    value: 10
  eval-num-processes:
    value: 1
  num-render:
    value: 1000
  eval-interval:
    value: 2000
  num-eval:
    value: 100
  lr:
    value: 0.0001
  log-interval:
    value: 1000
  save-interval:
    value: 50000
  bc-state-norm:
    value: False
  il-in-action-norm:
    value: False 
  il-out-action-norm:
    value: False
  clip-actions:
    value: True
  stochastic-optimizer-train_samples:
    value: 256
  traj-batch-size:
    value: 512
  hidden-dim:
    value: 1024
  depth:
    value: 1
  max-grad-norm:
    value: -1
  noise-ratio: 
    value: 2.00
  goal-noise-ratio:
    value: 2.00
