project: 'diffusion'
program: dbc/main.py
method: grid
name: Push-dbc-1.50

parameters:
  seed:
    # values: [1, 2, 3]
    value: 1
  prefix:
    value: "dbc"
  alg:
    value: "dbc"
  traj-load-path:
    value: "./expert_datasets/push_10000_clip.pt"
  ddpm-path:
    value: "push_10000_clip_ddpm.pt"
  coeff:
    # values: [0.1, 1, 2]
    value: 1
  coeff-bc:
    values: [0, 0.1, 1]
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 100
  lr:
    # values: [0.0001, 0.00001, 0.000001]
    value: 0.00001
  log-interval:
    value: 2000
  save-interval:
    value: 100000
  eval-interval:
    value: 4000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  hidden-dim:
    value: 1024
  depth:
    value: 1
  max-grad-norm:
    value: -1
  noise-ratio: 
    value: 1.50
  goal-noise-ratio:
    value: 1.50
