project: "DBC-ICLR"
program: dbc/main.py
method: grid
name: "AntGoal-v0_ICLR"

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "dbc"
  alg:
    value: "dbc"
  traj-load-path:
    value: "./expert_datasets/ant_25000.pt"
  ddpm-path:
    value: "/home/mhhsu/dbc-private/ant_25000_ddpm.pt"
  env-name:
    value: "AntGoal-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 8000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 100
  lr:
    value: 0.01
  log-interval:
    value: 200
  save-interval:
    value: 100000
  eval-interval:
    value: 1000
  bc-state-norm:
    value: False
  il-in-action-norm:
    value: False
  il-out-action-norm:
    value: False
  clip-actions:
    value: True
  coeff:
    value: 1
  ant-noise:
    value: 0.01
  traj-frac:
    value: 1.0
  fix-step-when-get-loss:
    value: True
  fix-which-step-when-get-loss:
    value: 249
  hidden-dim:
    value: 1024
