project: 'diffusion'
program: dbc/main.py
method: grid

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "dp"
  alg:
    value: "dp"
  traj-load-path:
    value: "./expert_datasets/hand_10000_v2.pt"
  env-name:
    value: "CustomHandManipulateBlockRotateZ-v2"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 30000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 3
  vid-fps:
    value: 30
  num-eval:
    value: 10
  lr:
    value: 0.0001
  log-interval:
    value: 2000
  save-interval:
    value: 100000
  eval-interval:
    value: 20000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
