project: 'diffusion'
program: dbc/main.py
method: grid
name: Pick-bc-1.75

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "bc"
  alg:
    value: "bc"
  traj-load-path:
    value: "./expert_datasets/pick_10000_clip.pt"
  env-name:
    value: "FetchPickAndPlaceDiffHoldout-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 1
  cuda:
    value: True
  num-render:
    value: 1
  num-eval:
    value: 100
  vid-fps:
    value: 100
  lr:
    value: 0.00001
  log-interval:
    value: 2000
  save-interval:
    value: 100000
  eval-interval:
    value: 2000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  traj-batch-size:
    value: 128
  hidden-dim:
    value: 1024
  depth:
    value: 1
  max-grad-norm:
    value: -1
  noise-ratio: 
    value: 1.75
  goal-noise-ratio:
    value: 1.75
