project: 'diffusion'
program: dbc/main.py
method: grid
name: Pick-dp-2.00

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "diff-policy"
  alg:
    value: "diff-policy"
  traj-load-path:
    value: "./expert_datasets/pick_10000_clip.pt"
  env-name:
    value: "FetchPickAndPlaceDiffHoldout-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 15000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  vid-fps:
    value: 30
  num-eval:
    value: 10
  lr:
    value: 0.00001
  log-interval:
    value: 3000
  save-interval:
    value: 500000
  eval-interval:
    value: 9000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  traj-batch-size:
    value: 128
  hidden-dim:
    value: 1200
  depth:
    value: 4
  noise-ratio: 
    value: 2.00
  goal-noise-ratio:
    value: 2.00
