project: 'diffusion'
program: dbc/main.py
method: grid
name: Pick-dbc-1.25

parameters:
  seed:
    # values: [1, 2, 3]
    value: 1
  prefix:
    value: "dbc"
  alg:
    value: "dbc"
  traj-load-path:
    value: "./expert_datasets/pick_10000_clip.pt"
  ddpm-path:
    value: "pick_10000_clip_ddpm.pt"
  env-name:
    value: "FetchPickAndPlaceDiffHoldout-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 10
  coeff:
    value: 1
    # values: [0.5, 1, 2]
  coeff-bc:
    values: [0, 0.1, 1]
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 10
  lr:
    # values: [0.0001, 0.00001, 0.000001]
    value: 0.00001
  log-interval:
    value: 1000
  save-interval:
    value: 100000
  eval-interval:
    value: 3000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  traj-batch-size:
    value: 128
  hidden-dim:
    value: 1024
  depth:
    value: 1
  max-grad-norm:
    value: -1
  noise-ratio: 
    value: 1.25
  goal-noise-ratio:
    value: 1.25
